### ISSUE TITLE
Weird warning on install

### ISSUE THREAD

**Issue by gui11aume** [cellcomplexitylab/gufi#2]
Running `conda env create -f env.yml ` in commit `41a42e58` on Ubuntu 20 produces what seems to be an infinite amount of the warning below (and does not seem to create the environment).

```Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.```

**Comment by Anshul22Verma** [comment]
Sure this is a warning, but I will correct it so that it doesn't appear.

**Comment by Anshul22Verma** [comment]
Hi @gui11aume, can you please put a **screen-shot** of this error because I am not able to regenerate this `error/warning` in the my **conda terminal**.  I have replaced the conda's `env.yml` with `requirements.txt`, please let me know if this issue persists with this new file as well, I am closing this issue feel free to reopen it.  

(It was just to do with mentioning the pip version for the anaconda environment, I could have fixed it but I have removed it altogether, considering we are using Linux and we do not need anaconda).
